### PR TITLE
Kmek branch

### PR DESCRIPTION
**Pull request by Kmek**
renamed the branch

### CODE REVIEW

**Comment by Kmek** [comment]
"Added buttons" - Only the two buttons to toggle the ports & the start timer button work, the rest aren't connected to anything yet. The start/stop timer button only toggles drawing on the canvas right now, not the timer yet.

**Comment by Kmek** [comment]
"Particles stay inside the canvas" - Particles pick a new location and check if it is inside the canvas. If the new location is outside, then another new location is picked over and over again. This prevents each particle from going beyond the canvas. But particles currently ignore the closed ports and center wall.

**Comment by Kmek** [comment]
- Also added a text input for the timer (everything pauses when the timer reaches zero) and made the reset simulation button reset all of the particles back into their starting positions. Particles now start in a 7 by 10 array with 2 big particles and 52 lil particles.

**Review by chanimores — COMMENTED** [review]
Kate and I looked at this together, I'm merging it. Looks good!

**Pull request merged**
